// Race Status
export enum RaceStatus {
    NOT_STARTED = 'NOT_STARTED',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED',
    RED_FLAG = 'RED_FLAG',
    SAFETY_CAR = 'SAFETY_CAR',
    VIRTUAL_SAFETY_CAR = 'VIRTUAL_SAFETY_CAR'
}